/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentFiVaultV2 {
  export type PoolStruct = {
    creator: AddressLike;
    totalSupply: BigNumberish;
    virtualUsdcReserve: BigNumberish;
    virtualTokenReserve: BigNumberish;
    realUsdcBalance: BigNumberish;
    active: boolean;
  };

  export type PoolStructOutput = [
    creator: string,
    totalSupply: bigint,
    virtualUsdcReserve: bigint,
    virtualTokenReserve: bigint,
    realUsdcBalance: bigint,
    active: boolean
  ] & {
    creator: string;
    totalSupply: bigint;
    virtualUsdcReserve: bigint;
    virtualTokenReserve: bigint;
    realUsdcBalance: bigint;
    active: boolean;
  };
}

export interface AgentFiVaultV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS"
      | "CREATOR_ALLOC"
      | "CREATOR_FEE_BPS"
      | "FEE_BPS"
      | "INITIAL_TOKEN_RESERVE"
      | "INITIAL_USDC_RESERVE"
      | "PROTOCOL_FEE_BPS"
      | "allPools"
      | "backend"
      | "balanceOf"
      | "buy"
      | "createPool"
      | "getBuyQuote"
      | "getMarketCap"
      | "getPool"
      | "getPoolCount"
      | "getPrice"
      | "getSellQuote"
      | "holderCount"
      | "pools"
      | "sell"
      | "setBackend"
      | "setTreasury"
      | "treasury"
      | "usdc"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PoolCreated" | "Trade"): EventFragment;

  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CREATOR_ALLOC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CREATOR_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "INITIAL_TOKEN_RESERVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_USDC_RESERVE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PROTOCOL_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "backend", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buy",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPool",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyQuote",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketCap",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getPool", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getPoolCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getSellQuote",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "holderCount",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pools", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "sell",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setBackend",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CREATOR_ALLOC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CREATOR_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_TOKEN_RESERVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_USDC_RESERVE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PROTOCOL_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allPools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "backend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBuyQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketCap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pools", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBackend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace PoolCreatedEvent {
  export type InputTuple = [postId: BytesLike, creator: AddressLike];
  export type OutputTuple = [postId: string, creator: string];
  export interface OutputObject {
    postId: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeEvent {
  export type InputTuple = [
    postId: BytesLike,
    trader: AddressLike,
    isBuy: boolean,
    usdcAmount: BigNumberish,
    tokenAmount: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [
    postId: string,
    trader: string,
    isBuy: boolean,
    usdcAmount: bigint,
    tokenAmount: bigint,
    newPrice: bigint
  ];
  export interface OutputObject {
    postId: string;
    trader: string;
    isBuy: boolean;
    usdcAmount: bigint;
    tokenAmount: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentFiVaultV2 extends BaseContract {
  connect(runner?: ContractRunner | null): AgentFiVaultV2;
  waitForDeployment(): Promise<this>;

  interface: AgentFiVaultV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS: TypedContractMethod<[], [bigint], "view">;

  CREATOR_ALLOC: TypedContractMethod<[], [bigint], "view">;

  CREATOR_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  INITIAL_TOKEN_RESERVE: TypedContractMethod<[], [bigint], "view">;

  INITIAL_USDC_RESERVE: TypedContractMethod<[], [bigint], "view">;

  PROTOCOL_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  allPools: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  backend: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  buy: TypedContractMethod<
    [postId: BytesLike, usdcAmount: BigNumberish, minTokensOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPool: TypedContractMethod<
    [postId: BytesLike, creator: AddressLike],
    [void],
    "nonpayable"
  >;

  getBuyQuote: TypedContractMethod<
    [postId: BytesLike, usdcAmount: BigNumberish],
    [bigint],
    "view"
  >;

  getMarketCap: TypedContractMethod<[postId: BytesLike], [bigint], "view">;

  getPool: TypedContractMethod<
    [postId: BytesLike],
    [AgentFiVaultV2.PoolStructOutput],
    "view"
  >;

  getPoolCount: TypedContractMethod<[], [bigint], "view">;

  getPrice: TypedContractMethod<[postId: BytesLike], [bigint], "view">;

  getSellQuote: TypedContractMethod<
    [postId: BytesLike, tokenAmount: BigNumberish],
    [bigint],
    "view"
  >;

  holderCount: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  pools: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        creator: string;
        totalSupply: bigint;
        virtualUsdcReserve: bigint;
        virtualTokenReserve: bigint;
        realUsdcBalance: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  sell: TypedContractMethod<
    [postId: BytesLike, tokenAmount: BigNumberish, minUsdcOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  setBackend: TypedContractMethod<
    [_backend: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CREATOR_ALLOC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CREATOR_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_TOKEN_RESERVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INITIAL_USDC_RESERVE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PROTOCOL_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allPools"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "backend"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [postId: BytesLike, usdcAmount: BigNumberish, minTokensOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createPool"
  ): TypedContractMethod<
    [postId: BytesLike, creator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBuyQuote"
  ): TypedContractMethod<
    [postId: BytesLike, usdcAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMarketCap"
  ): TypedContractMethod<[postId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPool"
  ): TypedContractMethod<
    [postId: BytesLike],
    [AgentFiVaultV2.PoolStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPoolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[postId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSellQuote"
  ): TypedContractMethod<
    [postId: BytesLike, tokenAmount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "holderCount"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pools"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        creator: string;
        totalSupply: bigint;
        virtualUsdcReserve: bigint;
        virtualTokenReserve: bigint;
        realUsdcBalance: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<
    [postId: BytesLike, tokenAmount: BigNumberish, minUsdcOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBackend"
  ): TypedContractMethod<[_backend: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PoolCreated"
  ): TypedContractEvent<
    PoolCreatedEvent.InputTuple,
    PoolCreatedEvent.OutputTuple,
    PoolCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Trade"
  ): TypedContractEvent<
    TradeEvent.InputTuple,
    TradeEvent.OutputTuple,
    TradeEvent.OutputObject
  >;

  filters: {
    "PoolCreated(bytes32,address)": TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;
    PoolCreated: TypedContractEvent<
      PoolCreatedEvent.InputTuple,
      PoolCreatedEvent.OutputTuple,
      PoolCreatedEvent.OutputObject
    >;

    "Trade(bytes32,address,bool,uint256,uint256,uint256)": TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
    Trade: TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
  };
}
