/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentRegistry {
  export type AgentDataStruct = {
    humanId: BytesLike;
    ensName: string;
    templateType: string;
    active: boolean;
    registeredAt: BigNumberish;
  };

  export type AgentDataStructOutput = [
    humanId: string,
    ensName: string,
    templateType: string,
    active: boolean,
    registeredAt: bigint
  ] & {
    humanId: string;
    ensName: string;
    templateType: string;
    active: boolean;
    registeredAt: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentList"
      | "agentToHuman"
      | "agents"
      | "backend"
      | "deactivateAgent"
      | "getAgent"
      | "getAgentCount"
      | "humanToAgent"
      | "isVerifiedAgent"
      | "registerAgent"
      | "setBackend"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentDeactivated" | "AgentRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentToHuman",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "backend", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deactivateAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "humanToAgent",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifiedAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BytesLike, AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setBackend",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "agentList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agentToHuman",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "backend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "humanToAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVerifiedAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBackend", data: BytesLike): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [agentWallet: AddressLike];
  export type OutputTuple = [agentWallet: string];
  export interface OutputObject {
    agentWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    humanId: BytesLike,
    agentWallet: AddressLike,
    ensName: string
  ];
  export type OutputTuple = [
    humanId: string,
    agentWallet: string,
    ensName: string
  ];
  export interface OutputObject {
    humanId: string;
    agentWallet: string;
    ensName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agentToHuman: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean, bigint] & {
        humanId: string;
        ensName: string;
        templateType: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  backend: TypedContractMethod<[], [string], "view">;

  deactivateAgent: TypedContractMethod<
    [agentWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  getAgent: TypedContractMethod<
    [wallet: AddressLike],
    [AgentRegistry.AgentDataStructOutput],
    "view"
  >;

  getAgentCount: TypedContractMethod<[], [bigint], "view">;

  humanToAgent: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  isVerifiedAgent: TypedContractMethod<
    [wallet: AddressLike],
    [boolean],
    "view"
  >;

  registerAgent: TypedContractMethod<
    [
      humanId: BytesLike,
      agentWallet: AddressLike,
      ensName: string,
      templateType: string
    ],
    [void],
    "nonpayable"
  >;

  setBackend: TypedContractMethod<
    [_backend: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agentToHuman"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, boolean, bigint] & {
        humanId: string;
        ensName: string;
        templateType: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "backend"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deactivateAgent"
  ): TypedContractMethod<[agentWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [AgentRegistry.AgentDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "humanToAgent"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isVerifiedAgent"
  ): TypedContractMethod<[wallet: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      humanId: BytesLike,
      agentWallet: AddressLike,
      ensName: string,
      templateType: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBackend"
  ): TypedContractMethod<[_backend: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(address)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentRegistered(bytes32,address,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
  };
}
