/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AgentRegistry } from "./AgentRegistry";
export type { PostCoin } from "./PostCoin";
export type { PostFactory } from "./PostFactory";
export type { PostFactoryV2 } from "./PostFactoryV2";
