/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PostFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentRegistry"
      | "agentToPosts"
      | "allPosts"
      | "backend"
      | "contentHashToCoin"
      | "createPost"
      | "getAgentPosts"
      | "getAllPosts"
      | "getCoinByHash"
      | "getPostCount"
      | "setBackend"
      | "treasury"
      | "usdcAddress"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PostCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "agentRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentToPosts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allPosts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "backend", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contentHashToCoin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPost",
    values: [AddressLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentPosts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPosts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCoinByHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPostCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBackend",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "usdcAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "agentRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentToPosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allPosts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "backend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contentHashToCoin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentPosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllPosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCoinByHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPostCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBackend", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usdcAddress",
    data: BytesLike
  ): Result;
}

export namespace PostCreatedEvent {
  export type InputTuple = [
    agentWallet: AddressLike,
    coinAddress: AddressLike,
    contentHash: BytesLike,
    ticker: string
  ];
  export type OutputTuple = [
    agentWallet: string,
    coinAddress: string,
    contentHash: string,
    ticker: string
  ];
  export interface OutputObject {
    agentWallet: string;
    coinAddress: string;
    contentHash: string;
    ticker: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PostFactory extends BaseContract {
  connect(runner?: ContractRunner | null): PostFactory;
  waitForDeployment(): Promise<this>;

  interface: PostFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentRegistry: TypedContractMethod<[], [string], "view">;

  agentToPosts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  allPosts: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  backend: TypedContractMethod<[], [string], "view">;

  contentHashToCoin: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  createPost: TypedContractMethod<
    [agentWallet: AddressLike, contentHash: BytesLike, ticker: string],
    [string],
    "nonpayable"
  >;

  getAgentPosts: TypedContractMethod<[agent: AddressLike], [string[]], "view">;

  getAllPosts: TypedContractMethod<[], [string[]], "view">;

  getCoinByHash: TypedContractMethod<
    [contentHash: BytesLike],
    [string],
    "view"
  >;

  getPostCount: TypedContractMethod<[], [bigint], "view">;

  setBackend: TypedContractMethod<
    [_backend: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdcAddress: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agentToPosts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "allPosts"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "backend"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "contentHashToCoin"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<
    [agentWallet: AddressLike, contentHash: BytesLike, ticker: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAgentPosts"
  ): TypedContractMethod<[agent: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllPosts"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCoinByHash"
  ): TypedContractMethod<[contentHash: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getPostCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setBackend"
  ): TypedContractMethod<[_backend: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdcAddress"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "PostCreated"
  ): TypedContractEvent<
    PostCreatedEvent.InputTuple,
    PostCreatedEvent.OutputTuple,
    PostCreatedEvent.OutputObject
  >;

  filters: {
    "PostCreated(address,address,bytes32,string)": TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
    PostCreated: TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
  };
}
