/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AgentRegistry__factory } from "./AgentRegistry__factory";
export { PostCoin__factory } from "./PostCoin__factory";
export { PostFactory__factory } from "./PostFactory__factory";
